Remove EMBER_CLI_FASTBOOT environment variable and not include fastbo…
tomdale/ember-network pull request #20
Opened 2017-05-12 22:44 UTC by tsubomii

This change makes ember-network work with ember-cli-fastboot 1.0.  It's backwards compatible. Works with ember-cli-fastboot that generates double build and without render using fastboot.

2017-05-14 00:51 UTC, kratiahuja commented
I think `ember-network` has no fastboot tests. It would be nice to have some tests in here to make sure it works in CI too.

2017-06-03 16:54 UTC, kellyselden requested changes
Version issue

2017-06-03 16:54 UTC, kellyselden commented on package.json
> +  "version": "0.3.2",
The version bump should be independent of this PR

2017-06-03 17:04 UTC, kellyselden commented
I got `BroccoliMergeTrees: Expected Broccoli node, got undefined for inputNodes[0]` when trying this branch out.

2017-06-04 18:00 UTC, kratiahuja commented
@kellyselden these changes are same as `ember-fetch` which worked for me. Did you try it in a dummy app?

2017-06-06 14:04 UTC, tomdale commented on package.json
> +  "version": "0.3.2",
@kellyselden is right, would you mind removing this from the PR? We will bump the version in the `package.json` when we publish to npm.

2017-06-06 20:09 UTC, tsubomii commented
@kellyselden  I tried your app. The build works after I upgrade to ember-cli 2.14.0-beta.2, that’s the compatible version with ember-cli-fastboot 1.0 .

2017-06-07 15:44 UTC, tomdale commented
Thanks @tsubomii!

2017-06-07 15:44 UTC, merged